version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ned-kelly-criterion"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1igar2vxauma8"
s3_prefix = "ned-kelly-criterion"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
