version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ned-kelly-criterion"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ch9ldxpqx9pm"
s3_prefix = "ned-kelly-criterion"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
